package com.brocade.dcm.domain.model;

import java.io.Serializable;
import java.util.Objects;

/**
 * Dept definition.
 * 
 * This file was generated by Ignite Web Console (07/31/2017, 01:43)
 **/
public class Dept implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    private String deptid;

    /** Value for dname. */
    private String dname;

    /** Value for loc. */
    private String loc;

    public String getDeptid() {
		return deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	/**
     * Gets dname
     * 
     * @return Value for dname.
     **/
    public String getDname() {
        return dname;
    }

    /**
     * Sets dname
     * 
     * @param dname New value for dname.
     **/
    public void setDname(String dname) {
        this.dname = dname;
    }

    /**
     * Gets loc
     * 
     * @return Value for loc.
     **/
    public String getLoc() {
        return loc;
    }

    /**
     * Sets loc
     * 
     * @param loc New value for loc.
     **/
    public void setLoc(String loc) {
        this.loc = loc;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Dept))
            return false;
        
        Dept that = (Dept)o;

        if (Objects.equals(deptid, that.deptid)) {
			System.out.println("*********EQUALS HIT CHECK*********");
			return true;
		}
		return false;

        /*if (dname != null ? !dname.equals(that.dname) : that.dname != null)
            return false;
        

        if (loc != null ? !loc.equals(that.loc) : that.loc != null)
            return false;
        
        return true;*/
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
    	final int prime = 31;
		int result = 1;
		result = prime * result + Objects.hashCode(deptid);
		return result;
        /*int res = dname != null ? dname.hashCode() : 0;

        res = 31 * res + (loc != null ? loc.hashCode() : 0);

        return res;*/
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Dept [" + 
        	"deptid=" + deptid + ", " + 
            "dname=" + dname + ", " + 
            "loc=" + loc +
        "]";
    }
}