package com.brocade.dcm.domain.model;

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

/**
 * Emp definition.
 * 
 * This file was generated by Ignite Web Console (07/31/2017, 01:43)
 **/
public class Emp implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    private String empid;

    /** Value for ename. */
    private String ename;

    /** Value for job. */
    private String job;

    /** Value for mgr. */
    private String mgr;

    /** Value for hiredate. */
    private Date hiredate;

    /** Value for sal. */
    private Integer sal;

    /** Value for comm. */
    private Integer comm;

    /** Value for deptid. */
    private String deptid;

    public String getEmpid() {
		return empid;
	}

	public void setEmpid(String empid) {
		this.empid = empid;
	}

	/**
     * Gets ename
     * 
     * @return Value for ename.
     **/
    public String getEname() {
        return ename;
    }

    /**
     * Sets ename
     * 
     * @param ename New value for ename.
     **/
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * Gets job
     * 
     * @return Value for job.
     **/
    public String getJob() {
        return job;
    }

    /**
     * Sets job
     * 
     * @param job New value for job.
     **/
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * Gets mgr
     * 
     * @return Value for mgr.
     **/
    public String getMgr() {
        return mgr;
    }

    /**
     * Sets mgr
     * 
     * @param mgr New value for mgr.
     **/
    public void setMgr(String mgr) {
        this.mgr = mgr;
    }

    /**
     * Gets hiredate
     * 
     * @return Value for hiredate.
     **/
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * Sets hiredate
     * 
     * @param hiredate New value for hiredate.
     **/
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * Gets sal
     * 
     * @return Value for sal.
     **/
    public Integer getSal() {
        return sal;
    }

    /**
     * Sets sal
     * 
     * @param sal New value for sal.
     **/
    public void setSal(Integer sal) {
        this.sal = sal;
    }

    /**
     * Gets comm
     * 
     * @return Value for comm.
     **/
    public Integer getComm() {
        return comm;
    }

    /**
     * Sets comm
     * 
     * @param comm New value for comm.
     **/
    public void setComm(Integer comm) {
        this.comm = comm;
    }

    /**
     * Gets deptid
     * 
     * @return Value for deptid.
     **/
    public String getDeptid() {
        return deptid;
    }

    /**
     * Sets deptid
     * 
     * @param deptid New value for deptid.
     **/
    public void setDeptid(String deptid) {
        this.deptid = deptid;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Emp))
            return false;
        
        Emp that = (Emp)o;

        if (Objects.equals(empid, that.empid)) {
			System.out.println("*********EQUALS HIT CHECK*********");
			return true;
		}
		return false;

        /*if (ename != null ? !ename.equals(that.ename) : that.ename != null)
            return false;
        

        if (job != null ? !job.equals(that.job) : that.job != null)
            return false;
        

        if (mgr != null ? !mgr.equals(that.mgr) : that.mgr != null)
            return false;
        

        if (hiredate != null ? !hiredate.equals(that.hiredate) : that.hiredate != null)
            return false;
        

        if (sal != null ? !sal.equals(that.sal) : that.sal != null)
            return false;
        

        if (comm != null ? !comm.equals(that.comm) : that.comm != null)
            return false;
        

        if (deptid != null ? !deptid.equals(that.deptid) : that.deptid != null)
            return false;
        
        return true;*/
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
    	final int prime = 31;
		int result = 1;
		result = prime * result + Objects.hashCode(empid);
		return result;
        /*int res = ename != null ? ename.hashCode() : 0;

        res = 31 * res + (job != null ? job.hashCode() : 0);

        res = 31 * res + (mgr != null ? mgr.hashCode() : 0);

        res = 31 * res + (hiredate != null ? hiredate.hashCode() : 0);

        res = 31 * res + (sal != null ? sal.hashCode() : 0);

        res = 31 * res + (comm != null ? comm.hashCode() : 0);

        res = 31 * res + (deptid != null ? deptid.hashCode() : 0);

        return res;*/
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Emp [" + 
        	"empid=" + empid + ", " + 
            "ename=" + ename + ", " + 
            "job=" + job + ", " + 
            "mgr=" + mgr + ", " + 
            "hiredate=" + hiredate + ", " + 
            "sal=" + sal + ", " + 
            "comm=" + comm + ", " + 
            "deptid=" + deptid +
        "]";
    }
}